version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - ollama-network

  server:
    build:
      context: .
    container_name: flask-server
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge

